services:
  web-metas:
    image: nginx:stable-alpine3.19-slim
    restart: always
    container_name: web_metas_container
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-metas
    networks:
      - red-gane-int

  api-metas:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_metas_container
    restart: always
    image: api-metas:v2.3
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota

networks:
  red-gane-int:
    external: true
    